//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGenConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        public static byte[] Template { get; internal set; }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftGenConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileView {
            get {
                object obj = ResourceManager.GetObject("fileView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileView1 {
            get {
                object obj = ResourceManager.GetObject("fileView1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap form1Edit {
            get {
                object obj = ResourceManager.GetObject("form1Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap form1EndEdit {
            get {
                object obj = ResourceManager.GetObject("form1EndEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap form2Add_32 {
            get {
                object obj = ResourceManager.GetObject("form2Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Form2EditLine_32 {
            get {
                object obj = ResourceManager.GetObject("Form2EditLine_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_list_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_add_list_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_file_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_save_file_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_view_file_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_view_file_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_48 {
            get {
                object obj = ResourceManager.GetObject("info_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payConverter {
            get {
                object obj = ResourceManager.GetObject("payConverter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Banks&gt;
        ///  &lt;bank id=&quot;0&quot;&gt;
        ///    &lt;NAME&gt;Райффайзен Банк Аваль&lt;/NAME&gt;
        ///    &lt;RAHUNOK&gt;UA643808050000000000265043345&lt;/RAHUNOK&gt;
        ///    &lt;MFO&gt;313849&lt;/MFO&gt;
        ///    &lt;EDRPOU&gt;&lt;/EDRPOU&gt;
        ///    &lt;clientBankCode&gt;40375721&lt;/clientBankCode&gt;
        ///  &lt;/bank&gt;
        ///  &lt;bank id=&quot;1&quot;&gt;
        ///    &lt;NAME&gt;УкрГазБанк&lt;/NAME&gt;
        ///    &lt;RAHUNOK&gt;26545743585101.980&lt;/RAHUNOK&gt;
        ///    &lt;MFO&gt;&lt;/MFO&gt;
        ///    &lt;EDRPOU&gt;40375721&lt;/EDRPOU&gt;
        ///    &lt;clientBankCode&gt;&lt;/clientBankCode&gt;
        ///    &lt;IBAN&gt;UA383204780000026545743585101&lt;/IBAN&gt;
        ///  &lt;/bank&gt;
        ///  &lt;bank id=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayConverterConfig {
            get {
                return ResourceManager.GetString("PayConverterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NewDataSet&gt;
        ///  &lt;Employee&gt;
        ///    &lt;NAME&gt;ЮЛIЯ БУНIНА АКАДЕМIКА ЯНГЕЛЯ,36,КВ1&lt;/NAME&gt;
        ///    &lt;ERDPO&gt;21560766&lt;/ERDPO&gt;
        ///    &lt;RRahunok&gt;UA463003460000026007010194910&lt;/RRahunok&gt;
        ///    &lt;Comment&gt;null&lt;/Comment&gt;
        ///  &lt;/Employee&gt;
        ///  &lt;Employee&gt;
        ///    &lt;NAME&gt;КУЗЬМЕНКО   ТАМАРА ВАСИЛІВНА &lt;/NAME&gt;
        ///    &lt;ERDPO&gt;26243349&lt;/ERDPO&gt;
        ///    &lt;RRahunok&gt;UA568201720314281001201062742&lt;/RRahunok&gt;
        ///    &lt;Comment&gt;null&lt;/Comment&gt;
        ///  &lt;/Employee&gt;
        ///  &lt;Employee&gt;
        ///    &lt;NAME&gt;БАБІНА ГАЛИНА ПАВЛІВНА &lt;/NAME&gt;
        ///    &lt;ERDPO&gt;262 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayConverterData {
            get {
                return ResourceManager.GetString("PayConverterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playVideo_32 {
            get {
                object obj = ResourceManager.GetObject("playVideo_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PRP_32 {
            get {
                object obj = ResourceManager.GetObject("PRP_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
